### ISSUE TITLE
SQLAlchemy i Alembic

### ISSUE THREAD

**Issue by magul** [CodeForPoznan/alinka-pyside#1]
* Przygotować modele bazy danych w SQLAlchemy z migracjami w Alembicu.
* Inicjalna wersja powinna implementować schemę bazy danych z https://github.com/codeforpoznan/alinka-tkinter
* baza inicjalizowana w pliku SQLite (podanie ścieżki do funkcji migracyjnej)

**Comment by w1stler** [comment]
@stanislawK will take over, as I am going away! ⛵
